name: automerge
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
jobs:
  automerge:
    if: "${{ !contains('!noautomerge', github.event.pull_request.body) }}"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - run: gh pr merge --squash $PULL_REQUEST
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PULL_REQUEST: ${{ github.event.pull_request.html_url }}

